apiVersion: v1
kind: Service
metadata:
  name: {{ include "conductor-ui.fullname" . }}-ui
  labels:
  {{- include "conductor-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.type }}
  selector:
    app: conductor-ui
  {{- include "conductor-ui.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ui.ports | toYaml | nindent 2 -}}