apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conductor-server.fullname" . }}
  labels:
    app: conductor-server
  {{- include "conductor-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.conductorServer.replicas }}
  selector:
    matchLabels:
      app: conductor-server
    {{- include "conductor-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: conductor-server
      {{- include "conductor-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: conductor-server
        image: {{ .Values.conductorServer.conductorServer.image.repository }}:{{ .Values.conductorServer.conductorServer.image.tag| default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources: {{- toYaml .Values.conductorServer.conductorServer.resources | nindent 10 }}
        volumeMounts:
        - name: workdir
          mountPath: "/app/config"
        env:
        - name: CONFIG_PROP
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: config_prop 

      initContainers:
      - name: install
        image: busybox:1.28
        args:
        - "/bin/sh"
        - "-c"
        - "printf \" #Servers.\n conductor.grpc-server.enabled=false\n \n # Database persistence type.\n conductor.db.type=postgres\n \n spring.datasource.url=jdbc:postgresql://$POSTGRES_ADDRPORT\n spring.datasource.username=$DB_USER\n spring.datasource.password=$DB_PASSWORD\n \n # Hikari pool sizes are -1 by default and prevent startup\n spring.datasource.hikari.maximum-pool-size=10\n spring.datasource.hikari.minimum-idle=2\n \n # Elastic search instance indexing is enabled.\n conductor.indexing.enabled=true\n conductor.elasticsearch.url=$ELASTICSEARCH_URL\n conductor.elasticsearch.indexName=conductor\n \n conductor.elasticsearch.clusterHealthColor=yellow\n \n conductor.workflow-status-listener.type=archive\n \n # Load sample kitchen sink workflow\n loadSample=true\n conductor.workflow-status-listener.type=stub\n\" | tee /initcontainer/initcontainer.properties"
        volumeMounts:
        - name: workdir
          # do not change only here, need to change also target of script above
          mountPath: "/initcontainer"
        env:
        - name: CONFIG_PROP
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: config_prop 
        - name: ELASTICSEARCH_URL 
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: elasticsearch_url
        - name: POSTGRES_ADDRPORT
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: postgres_addrport 
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: es7-postgres-secret
              key: db_user 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es7-postgres-secret
              key: db_password

      volumes:
      - name: workdir
        emptyDir: {}

      restartPolicy: Always
