version: '2.3'

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=conductor
      - POSTGRES_DB=conductor
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - internal

  conductor-server:
    image: conductor:server-postres
    volumes:
      - $PWD/docker/config/config-postgres.properties:/props/injected.properties
    depends_on:
      - postgres
    environment:
      - CONFIG_PROP=config-postgres.properties
      - ELASTICSEARCH_URL=http://es:9200
      - POSTGRES_ADDRPORT=postgres:5432/conductor
      - DB_USER=conductor
      - DB_PASSWORD=conductor

volumes:
  db:
    driver: local 
