apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-server
  namespace: conductor
  labels:
    app: conductor-server
spec:
  selector:
    matchLabels:
      app: conductor-server
  replicas: 1
  template:
    metadata:
      labels:
        app: conductor-server
    spec:
      containers:
        - name: conductor-server
          image: 242346083784.dkr.ecr.us-east-1.amazonaws.com/conductor-server-es6-redis:v3.10.0
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
          env:
            - name: CONFIG_PROP
              value: "config-redis.properties"
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch.conductor.svc.cluster.local:9200"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: db_password 
            - name: REDIS_ADDRPORT
              value: "redis.conductor.svc.cluster.local:6379"
            - name: REDIS_MODE
              value: redis_standalone
            - name: REDIS_ZONE1
              value: "1"
            - name: REDIS_USE_SSL
              value: "false"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config-redis
              mountPath: /props/injected.properties
                #subPath: injected.properties
      volumes:
        - name: config-redis 
          configMap:
            name: config-redis 
      restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-redis
  namespace: conductor
data:
  config-redis.properties: |
    conductor.grpc-server.enabled=false
    conductor.db.type=##REDIS_MODE##
    workflow.dynomite.cluster.name=redis
    conductor.redis.hosts=##REDIS_ADDRPORT##:##REDIS_ZONE1##:##DB_PASSWORD##
    workflow.namespace.prefix=conductor
    workflow.namespace.queue.prefix=conductor_queues
    queues.dynomite.nonQuorum.port=6379
    workflow.dynomite.cluster.hosts.useSSL=##REDIS_USE_SSL##
    conductor.indexing.enabled=true
    conductor.elasticsearch.url=##ELASTICSEARCH_URL##
    conductor.elasticsearch.indexName=conductor
    conductor.elasticsearch.clusterHealthColor=yellow
    conductor.workflow-status-listener.type=stub
    loadSample=true
---
apiVersion: v1
kind: Service
metadata:
  name: conductor-server
  namespace: conductor
spec:
  selector:
    app: conductor-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
