apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-server
  labels:
    app: conductor-server
  
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: conductor-server
    
  template:
    metadata:
      labels:
        app: conductor-server
    spec:
      containers:
      - name: conductor-server
        env:
        - name: CONFIG_PROP 
          valueFrom: 
            configMapKeyRef:
              name: es7-postgres-config
              key: config_prop 
        image: conductor:server 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "0.5"
            memory: 2Gi
          requests:
            cpu: "0.2"
            memory: 1Gi
        volumeMounts:
        - name: workdir
          mountPath: "/app/config"
      initContainers:
      - name: install
        image: busybox:1.28
        args:
        - "/bin/sh"
        - "-c"
        - "printf \"#Servers.\n conductor.grpc-server.enabled=false\n \n # Database persistence type.\n conductor.db.type=postgres\n \n spring.datasource.url=jdbc:postgresql://$POSTGRES_ADDRPORT?currentSchema=daconductor&ApplicationName=conductor\n spring.datasource.username=$DB_USER\n spring.datasource.password=$DB_PASSWORD\n \n # Hikari pool sizes are -1 by default and prevent startup\n spring.datasource.hikari.maximum-pool-size=10\n spring.datasource.hikari.minimum-idle=2\n \n # Elastic search instance indexing is enabled.\n conductor.indexing.enabled=true\n conductor.elasticsearch.url=$ELASTICSEARCH_URL\n conductor.elasticsearch.indexName=conductor\n \n conductor.elasticsearch.clusterHealthColor=yellow\n \n conductor.workflow-status-listener.type=archive\n \n # Load sample kitchen sink workflow\n loadSample=false\n conductor.workflow-status-listener.type=stub\n\" > /initcontainer/initcontainer.properties"
        volumeMounts:
        - name: workdir
          mountPath: "/initcontainer"
        env:
        - name: ELASTICSEARCH_URL 
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: elasticsearch_url
        - name: POSTGRES_ADDRPORT
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: postgres_addrport 
        - name: DB_USER 
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: db_user 
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: es7-postgres-config
              key: db_password

      volumes:
      - name: workdir
        emptyDir: {}

      restartPolicy: Always

