apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis 
  namespace: conductor
spec:
  selector:
    matchLabels:
      app: redis 
  serviceName: redis 
  replicas: 1
  template:
    metadata:
      labels:
        app: redis 
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        imagePullPolicy: Always
        args: ["--requirepass", "$(DB_PASSWORD)", "--loglevel", "warning" ]
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: MASTER
          value: "true"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: db_password 
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis 
  namespace: conductor
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis 
      protocol: TCP
      port: 6379 
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret 
type: Opaque
data:
  db_password: Tm90QVBhc3NXb3JkUmVhbGx5
